### ISSUE TITLE
Lingeling does not compile as shipped

### ISSUE THREAD

**Issue by msoos** [biotomas/ipasir#11]
As per shipped ZIP, lingeling does not compile with my version of gcc (9.2.1). 
It is missing `using std::sqrt`, most likely. Please compile with a compiler that's relatively new, it will fail.

```
[mkone.sh] building and linking application 'icnf' against 'lingelingbcj'
/usr/bin/ld: ../../sat/lingelingbcj//libipasirlingelingbcj.a(lglib.o): in function `lglstats':
lglib.c:(.text+0x6d335): undefined reference to `sqrt'
/usr/bin/ld: lglib.c:(.text+0x6d394): undefined reference to `sqrt'
/usr/bin/ld: lglib.c:(.text+0x6d3fb): undefined reference to `sqrt'
/usr/bin/ld: lglib.c:(.text+0x6d46a): undefined reference to `sqrt'
/usr/bin/ld: lglib.c:(.text+0x6d4e1): undefined reference to `sqrt'
/usr/bin/ld: ../../sat/lingelingbcj//libipasirlingelingbcj.a(lglib.o):lglib.c:(.text+0x6d55b): more undefined references to `sqrt' follow
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:59: icnf] Error 1
*** mkone: could not build 'app/icnf/icnf'
```

Please fix as soon as possible so I can compete in the 2020 competition. Thanks!
